server:
  port: 8088
spring:
  profiles:
    active: dev
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/person?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    check-template: false
    check-template-location: false
    mode: HTML5
  application:
    name: demo